[DRAFT] face landmarks detection
open-edge-platform/geti pull request #511
Opened 2021-04-01 06:05 UTC by ygnn123

2021-06-21 10:06 UTC, druzhkov-paul requested changes
General comments:

1. Please remove irrelevant code.
2. If you want to reuse some functionality, that was not implemented by you, please do that explicitly: base off of some branch, not just copy-and-paste code.
3. Please add readme file, where provided models are listed and steps to run training/evaluation/export are described. Take a look [here](https://github.com/openvinotoolkit/training_extensions/tree/develop/models/object_detection/model_templates/face-detection) for reference.

2021-06-21 12:48 UTC, ygnn123 commented on ote/requirements.txt
> +mmcv==1.2.7
Pip installs 1.3.5 version by default.  And last mmpose version have assert on version <1.3.0. Ok, I'm going change it. Thanks.

2021-11-02 08:26 UTC, Ilya-Krylov commented
@ygnn123 close or update

2022-02-15 15:03 UTC, nervana-ff commented
Can one of the admins verify this patch?

2022-09-16 09:35 UTC, closed without merging